name: Terraform Validation
on:
  - pull_request
jobs:
  terraform-fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
